language: objective-c
cache: false
addons:
  code_climate:
    repo_token:
      secure: a43RixcdMbAvLi941X2wgS5Xp/3BjhB1PH10wQxIIr+pk6awmhiEvWvPMUsx9wkkG9ajjb/5CcdAJ9QCFhajyS79vFXDQJmK60tj1SWSsClYUNAAHEbeYUr8XQbusnSIrxKRFyMF+GURrsGuIcMZphdZBbbWvlASsykrsenMUxU=
before_install:
  - (ruby --version)
  - sudo chown -R travis ~/Library/RubyMotion
  - mkdir -p ~/Library/RubyMotion/build
  - sudo motion update
install:
  - sudo gem install rspec
  - sudo gem install codeclimate-test-reporter
script:
  - rspec
  - cd ios-test-app
  - bundle install
  - pod setup > /dev/null
  - rake pod:install
  - rake spec iosversion=6.1
  - rake spec iosversion=7.1
  - rake spec iosversion=8.1
