#encoding: utf-8
#nd -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/android'

begin
  require 'bundler'
    Bundler.require(:development)
    Bundler.require(:default)
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.api_version = "21"
  app.target_api_version = "21"
  app.name = 'basicAndroidProject'
  app.sub_activities += %w(AbstractActivity)
  app.permissions << 'android.permission.WRITE_EXTERNAL_STORAGE'
  app.permissions << 'android.permission.READ_EXTERNAL_STORAGE'
end

