rake spec:device files=android_couch_db_spec,abstract_couch_db_spec
rake spec:device files=android_document_spec,abstract_document_spec
rake spec:device files=android_query_spec,abstract_query_spec
rake spec:device files=android_view_spec,abstract_view_spec
rake spec:device files=init_android_couchdb_spec,init_abstract_couchdb_spec
